package:
  name: nansat-libgdal
  version: "2.0.1"

source:
  url: http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  fn: libgdal-2.0.1.tar.gz
  md5: bdded121a62dae246d8500b42d87145b

build:
  number: 3 [linux64]
  number: 2 [linux32]

requirements:
  build:
    - hdf4
    - hdf5 1.8.15.1
    - libnetcdf
    - libdap
    - geos 3.3.3
    - proj4 4.9.1
    - libjasper
    - libxml2
  run:
    - hdf4
    - hdf5 1.8.15.1
    - libnetcdf
    - libdap
    - geos 3.3.3
    - proj4 4.9.1
    - libjasper
    - libxml2

#test:
#  commands:
#    - gdal_contour --help
#    - gdal_grid --help
#    - gdal_rasterize --help
#    - gdal_translate --help
#    - gdaladdo --help
#    - gdalenhance --help
#    - gdalwarp --help
#    - gdalinfo --formats

about:
  home: http://www.gdal.org/
  license: MIT
  summary: Geospatial Data Abstraction Library - With extra formats for nansat
