
package:
  name: szip
  version: 2.1

source:
  fn: szip-2.1.tar.gz
  url: http://www.hdfgroup.org/ftp/lib-external/szip/2.1/src/szip-2.1.tar.gz

build:
  number: 0 [linux64]
  number: 0 [linux32]


requirements:
  build:
    - m4

  run:
    - m4

test:
  imports:

  commands:

about:
  home: http://www.hdfgroup.org/doc_resource/SZIP/
  license: Free for non-commercial use

