package:
  name: libdap
#  version: "3.15.0"
  version: "3.12.0"

source:
  url: http://www.opendap.org/pub/source/libdap-3.12.0.tar.gz
#  url: ftp://ftp.nersc.no/pub/Aleks/libdap-3.15.0.tar.gz
  fn: libdap-3.12.0.tar.gz
#  fn: libdap-3.15.0.tar.gz

build:
  number: 1 [linux64]
  number: 0 [linux32]


requirements:
  build:
    - bison
    - libxml2
    - libgcc
    - automake
    - autoconf
    - libtool
    - flex
    - libuuid
    - curl
  run:
    - bison
    - libxml2
    - flex
    - libuuid
    - curl

about:
  home: http://www.opendap.org
  license: GNU LGPL
  summary: A C++ SDK which contains an implementation of DAP 2.0 and the development versions of DAP3, up to 3.4.
