package:
  name: nansat-netcdf
  version: "4.3.3.1"

source:
  url: https://github.com/Unidata/netcdf-c/archive/v4.3.3.1.tar.gz
  fn: netcdf-v4.3.3.1.tar.gz

build:
  number: 2 [linux64]
  number: 0 [linux32]


requirements:
  build:
    - hdf4
    - hdf5 1.8.15.1
    - szip
    - jpeg 8d
  run:
    - hdf4
    - hdf5 1.8.15.1
    - szip
    - jpeg 8d

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: http://www.unidata.ucar.edu/software/netcdf/copyright.html
  summary: NetCDF is a set of software libraries and self-describing, machine-independent data formats that support the creation, access, and sharing of array-oriented scientific data.
