package:
  name: nansat
  version: "0.6.6"
 
source:
  git_tag: v0.6.6
  git_url: https://github.com/nansencenter/nansat.git

build:
  number: 1
#  script: python setup.py install
 
requirements:
  build:
    - python
    - setuptools
    - numpy
    - pillow
    - netcdf4
    - scikit-learn
    - matplotlib
    - pyproj
    - basemap
    - nansat-libgdal
    - nansat-gdal
  run:
    - python
    - numpy
    - pillow
    - netcdf4
    - scikit-learn
    - matplotlib
    - pyproj
    - basemap
    - nansat-libgdal
    - nansat-gdal
 
#test:
#  imports:
#    - pyinstrument
 
about:
  home: https://github.com/nansencenter/nansat
  license: GNU GPLv3
  license_file: LICENSE
