package:
  name: bison
  version: 3.0.4

source:
  fn: bison-3.0.4.tar.gz
  url: http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz

build:
  number: 1  [linux64]
  number: 0 [linux32]


about:
    home: https://www.gnu.org/software/bison/
    license: GPL3

requirements:
  build:
    - m4 # [linux]
  
  run:
    - m4 # [linux]
