package:
  name: hdf4
  version: "4.2.11"

source:
  fn: hdf-4.2.11.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.11.tar.bz2

build:
  number: 1

requirements:
  build:
    - jpeg
    - zlib
    - bison
    - flex
  run:
    - jpeg
    - zlib
    - bison
    - flex
about:
    home: http://www.hdfgroup.org/HDF4/
    license: BSD-style (http://www.hdfgroup.org/ftp/HDF/current/src/unpacked/COPYING)
