package:
  name: nansat-gdal
  version: "2.0.1"

source:
  fn: GDAL-2.0.1.tar.gz
  url: https://pypi.python.org/packages/source/G/GDAL/GDAL-2.0.1.tar.gz
  patches:
    - prepend-dll.patch    [win]
    - clang.patch          [osx]
    - install_scripts.patch

build:
  number: 1 [linux64]
  number: 1 [linux32]

requirements:
  build:
    - python
    - nansat-libgdal
    - numpy 1.10.1
    - hdf4
    - hdf5 1.8.15.1
    - libdap 3.12.0
    - libnetcdf 4.3.3.1
    - libgcc
  run:
    - python
    - nansat-libgdal
    - numpy 1.10.1
    - hdf4
    - hdf5 1.8.15.1
    - libdap 3.12.0
    - libnetcdf 4.3.3.1
    - libgcc

about:
  home: https://pypi.python.org/pypi/GDAL/
  license: MIT
  summary: Geospatial Data Abstraction Library
