package:
  name: nansat-gdal
#  version: "1.11.2"
  version: "2.0.0"

source:
#  fn: gdal-1.11.2.tar.gz
  fn: GDAL-2.0.0.tar.gz
#  url: http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
  url: https://pypi.python.org/packages/source/G/GDAL/GDAL-2.0.0.tar.gz
  patches:
    - prepend-dll.patch    [win]
    - clang.patch          [osx]
    - install_scripts.patch

build:
  number: 4 [linux64]
  number: 0 [linux32]

requirements:
  build:
    - python
    - nansat-libgdal
    - numpy
    - hdf4
    - hdf5
    - libdap 3.12.0
    - libnetcdf
#    - nansat-netcdf
  run:
    - python
    - nansat-libgdal
    - numpy
    - hdf4
    - hdf5
    - libdap 3.12.0
    - libnetcdf
#    - nansat-netcdf

#test:
#  imports:
#    - osgeo.ogr
#    - osgeo.gdal

about:
  home: https://pypi.python.org/pypi/GDAL/
  license: MIT
  summary: Geospatial Data Abstraction Library
