package:
  name: flex
  version: 2.5.39

source:
  fn: flex-2.5.39.tar.gz # [linux]
  url: http://sourceforge.net/projects/flex/files/flex-2.5.39.tar.gz # [linux]

build:
  number: 1 [linux64]
  number: 1 [linux32]


about:
    home: http://flex.sourceforge.net/
    license: BSD

requirements:
  build:
    - m4 # [linux]

  run:
    - m4 # [linux]
