package:
  name: nansat-netcdf4-python
  version: "1.1.9"

source:
  fn: netcdf4-pythonv1.1.9rel.tar.gz
  url: https://github.com/Unidata/netcdf4-python/archive/v1.1.9rel.tar.gz

build:
  number: 0 [linux64]
  number: 0 [linux32]


requirements:
  build:
    - python 2.7.11
    - numpy 1.10.2
    - cython 0.23.4
## might need to recompile hdf5 with --enable-hl --enable-shared.
    - curl 7.45.0
    - hdf5 1.8.15.1
    - hdf4
    - nansat-netcdf
  run:
    - python 2.7.11
    - numpy 1.10.2
## might need to recompile hdf5 with --enable-hl --enable-shared.
    - curl 7.45.0
    - hdf5 1.8.15.1
    - hdf4
    - nansat-netcdf

about:
  home: http://unidata.github.io/netcdf4-python/
  license: https://github.com/Unidata/netcdf4-python/blob/master/COPYING
  summary: netcdf4-python is a Python interface to the netCDF C library.
