package:
  name: nansat-gdal
  version: "2.0.1"

source:
  fn: GDAL-2.0.1.tar.gz
  url: https://pypi.python.org/packages/source/G/GDAL/GDAL-2.0.1.tar.gz
  patches:
    - prepend-dll.patch    [win]
    - clang.patch          [osx]
    - install_scripts.patch

build:
  number: 2 [linux64]
  number: 1 [linux32]

requirements:
  build:
    - python 2.7.10
    - nansat-libgdal
    - numpy 1.10.2
    - hdf4
    - hdf5 1.8.15.1
    - libdap
    - libnetcdf 4.3.3.1
    - libgcc 4.8.5
  run:
    - python 2.7.10
    - nansat-libgdal
    - numpy 1.10.2
    - hdf4
    - hdf5 1.8.15.1
    - libdap
    - libnetcdf 4.3.3.1
    - libgcc 4.8.5

about:
  home: https://pypi.python.org/pypi/GDAL/
  license: MIT
  summary: Geospatial Data Abstraction Library
